### ISSUE TITLE
missing image upload button

### ISSUE THREAD

**Issue by admineral** [vercel-labs/ai-sdk-preview-attachments#2]
FYI, the attachment button is missing

**Comment by mellson** [comment]
Correct, there's no upload button right now, which is a bit confusing when first trying the code. Currently, it supports drag-and-drop and pasting the attachments. But I'm sure they would appreciate a PR adding a nice button.

**Comment by admineral** [comment]
I will ask magic ai to add a button

PR coming

Am 27.09.2024 um 08:34 schrieb Anders Bech Mellson ***@***.***>:

﻿

Correct, there's no upload button right now, which is a bit confusing when first trying the code. Currently, it supports drag-and-drop and pasting the attachments. But I'm sure they would appreciate a PR adding a nice button.
